UPSTREAM: src/lib: Add space before (
Fix the following error detected by checkpatch.pl:

ERROR: space required before the open parenthesis '('

 Conflicts:
	src/lib/delay.c
	src/lib/generic_dump_spd.c
	src/lib/memmove.c
	src/lib/spd_bin.c

TEST=Build and run on Galileo Gen2

Change-Id: I4df0f7f6d62561044605616aa623c2cfc2ccfa50
Signed-off-by: Patrick Georgi <pgeorgi@chromium.org>
Original-Commit-Id: 45fde705b627d6194f795237647ce42eb535d1c3
Original-Change-Id: I8953fecbe75136ff989c9e3cf6c5e155dcee3c3b
Original-Signed-off-by: Lee Leahy <Leroy.P.Leahy@intel.com>
Original-Reviewed-on: https://review.coreboot.org/18698
Original-Reviewed-by: Philippe Mathieu-Daud <philippe.mathieu.daude@gmail.com>
Original-Tested-by: build bot (Jenkins)
Original-Reviewed-by: Arthur Heymans <arthur@aheymans.xyz>
Reviewed-on: https://chromium-review.googlesource.com/452883
(cherry picked from commit 44ba4b7354c53bcc046dd2ba05c867f68fb60968)
Reviewed-on: https://chromium-review.googlesource.com/513248
Reviewed-by: Vadim Bendebury <vbendeb@chromium.org>
Commit-Queue: Vadim Bendebury <vbendeb@chromium.org>
Tested-by: Vadim Bendebury <vbendeb@chromium.org>
Trybot-Ready: Vadim Bendebury <vbendeb@chromium.org>